# Generated by Django 5.2.4 on 2025-07-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bike_tcp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bike',
        ),
        migrations.DeleteModel(
            name='mitesh',
        ),
        migrations.DeleteModel(
            name='Tcp',
        ),
    ]
