# Generated by Django 5.2.4 on 2025-07-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tcp',
        ),
    ]
