# Generated by Django 5.2.4 on 2025-07-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_tcp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mitesh',
        ),
    ]
