# Generated by Django 5.2.4 on 2025-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mitesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
