# Generated by Django 5.2.4 on 2025-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bike_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='bike',
        ),
        migrations.DeleteModel(
            name='mitesh',
        ),
    ]
