# Generated by Django 5.2.4 on 2025-07-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_h_delete_bike_delete_mitesh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h',
            old_name='Name',
            new_name='name',
        ),
    ]
