# Generated by Django 5.2.4 on 2025-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_name_h_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='h',
            name='image',
            field=models.ImageField(default=64, upload_to='tcp/'),
            preserve_default=False,
        ),
    ]
