# Generated by Django 5.2.4 on 2025-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='m',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m',
            name='password',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
