# Generated by Django 5.2.4 on 2025-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_name_m_first_name_m_last_name_m_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m',
            name='password',
            field=models.CharField(),
        ),
    ]
