# Generated by Django 5.2.4 on 2025-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=64),
            preserve_default=False,
        ),
    ]
